name: localtime
on: workflow_dispatch
jobs:
  get_localtime:
    name: Get Localtime
    runs-on: ubuntu-latest
    steps:
      - name: first_step
        env:
          LOCALTIME: $(date | cut -d' ' -f5)
        run: echo $LOCALTIME
