name: caller_workflow

on:
  workflow_dispatch:
    inputs:
      timezone:
        description: "Linux local timezone setup via timedatectl"
        required: true
        default: "America/Los_Angeles"
        type: string
      local_timezone:
        description: "Abbreviation for local timezone while in Daylight Savings Time (DST)"
        required: true
        default: 'PDT'
        type: string
      is_spoiler:
        description: "This info will spoil the movie for you (true|false)"
        default: true
        required: true
        type: boolean
      movie_info:
        description: "Enter information about the movie you are reviewing."
        default: "The protagonist dies at the end."
        required: true
        type: string

jobs:
    called_job_localtime:
      uses: ./.github/workflows/localtime.yml
    called_job_2:
      needs: called_job_localtime
      if: ${{ needs.called_job_localtime.outputs.daylight_savings_bool}}
      uses: ./.github/workflows/reusable_workflow.yml
      with:
        is_spoiler: ${{ inputs.is_spoiler }}
        movie_info: ${{ inputs.movie_info}}
