name: DST CRON

on:
  schedule:
    - cron: '10 4 * * 0-6'
    - cron: '20 4 * * 0-6'

jobs:
    called_job_localtime:
      uses: ./.github/workflows/localtime.yml
    called_job_2:
      needs: called_job_localtime
      if: ${{ (github.event.schedule == '10 4 * * 0-6' && needs.called_job_localtime.outputs.daylight_savings_bool == "true") || (github.event.schedule == '20 4 * * 0-6' && needs.called_job_localtime.outputs.daylight_savings_bool == "false")}}
      uses: ./.github/workflows/reusable_workflow.yml
      with:
        is_spoiler: false
        movie_info: "Nothing to see here."
