name: DST CRON

on:
  schedule:
    - cron: '55 2 * * 0-6'
    - cron: '05 3 * * 0-6'

jobs:
    called_job_localtime:
      uses: ./.github/workflows/localtime.yml
    called_job_2:
      needs: called_job_localtime
      if: ${{ (github.event.schedule == '55 2 * * 0-6' && needs.called_job_localtime.outputs.daylight_savings_bool == 1) || (github.event.schedule == '05 3 * * 0-6' && needs.called_job_localtime.outputs.daylight_savings_bool == 0)}}
      uses: ./.github/workflows/reusable_workflow.yml
      with:
        is_spoiler: false
        movie_info: "Nothing to see here."
