name: localtime

on: 
  workflow_call:
    inputs:
      timezone:
        required: false
        default: "America/LosAngeles"
        type: string

jobs:
  get_localtime:
    name: Get Localtime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: first_step
        id: localtime
        run: |
          sudo timedatectl set-timezone ""${{ inputs.timezone }}""
          echo "::set-output name=localtime::$(date | cut -d' ' -f5)"
      - name: second_step  
        if:  ${{ steps.localtime.outputs.localtime == 'PDT' }}
        run: echo "It's daylight savings time on the West Coast."
