name: localtime

on: 
  workflow_call:
    inputs:
      timezone:
        description: "Linux local timezone setup via timedatectl"
        required: true
        default: "America/Los_Angeles"
        type: string
      local_timezone:
        description: "Abbreviation for local timezone while in Daylight Savings Time (DST)"
        required: true
        default: 'PDT'
        type: string
    outputs:
      daylight_savings_bool:
        description: "Boolean value for whether or not it is daylight savings time in your timezone"
        value: ${{ jobs.get_localtime.outputs.daylight_savings_bool }}

jobs:
  get_localtime:
    name: Get Localtime
    runs-on: ubuntu-latest
    env:
      TIMEZONE: ${{ inputs.timezone }}
    outputs:
      daylight_savings_bool: ${{ steps.boolean_step.outputs.daylight_savings_bool }}
    steps:
      - name: setup_daylight_savings_time
        id: daylight_savings_abbreviation
        run: |
          sudo timedatectl set-timezone $TIMEZONE
          echo "::set-output name=daylight_savings::$(date | cut -d' ' -f5)"
      - name: second_step
        id: boolean_step
        if: ${{ steps.daylight_savings_abbreviation.outputs.daylight_savings == inputs.local_timezone }}
        run: echo "::set-output name=daylight_savings_bool::true"
