name: localtime

on: workflow_dispatch

jobs:
  get_localtime:
    name: Get Localtime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: first_step
        run: |
          sudo timedatectl set-timezone America/Los_Angeles
          echo "localtime=$(date | cut -d' ' -f5)" >> GITHUB_ENV
      - name: second_step  
        if:  github.env.localtime == 'PDT'
        run: echo "It\'s daylight savings time."

          
