name: localtime

on: workflow_dispatch

jobs:
  get_localtime:
    name: Get Localtime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: first_step
        run: |
          timedatectl set-timezone America/Los_Angeles
          LOCALTIME=$(date | cut -d' ' -f5)
          echo "$LOCALTIME"
        if: "$LOCALTIME" == "PDT"
          run: echo "It\'s daylight savings time."
          
