name: localtime

on: 
  workflow_call:
    inputs:
      timezone:
        description: "Linux local timezone setup with temp TZ var export"
        required: false
        default: "America/Los_Angeles"
        type: string
      local_timezone:
        description: "Abbreviation for local timezone while in Daylight Savings Time (DST)"
        required: false
        default: PDT
        type: string
    outputs:
      daylight_savings_bool:
        description: "Boolean value for whether or not it is daylight savings time in your timezone"
        value: ${{ jobs.get_localtime.outputs.daylight_savings_bool }}

jobs:
  get_localtime:
    name: Get Localtime
    runs-on: ubuntu-latest
    env:
      TIMEZONE: "${{ inputs.timezone }}"
      LOCAL_TIMEZONE: "${{ inputs.local_timezone }}"
    outputs:
      daylight_savings_bool: ${{ steps.return_daylight_savings_bool.outputs.daylight_savings_bool }}
    steps:
      - name: Setup Daylight Savings Time
        id: return_daylight_savings_bool
        run: |
          export TZ="$TIMEZONE"
          echo $(date)
          DST="$(date | cut -d' ' -f6)"
          echo "$DST"
          echo $(date | cut -d' ' -f1)
          echo $(date | cut -d' ' -f2)
          echo $(date | cut -d' ' -f3)
          echo $(date | cut -d' ' -f4)
          echo $(date | cut -d' ' -f5)
          [[ "$(date)" == *"$LOCAL_TIMEZONE"* ]] && echo "substring match" || echo "substring mismatch"
          if [ "$(date | cut -d' ' -f6)" = "$LOCAL_TIMEZONE" ]
          then
            echo "PDT in effect"
            echo "daylight_savings_bool=true" >> $GITHUB_OUTPUT
          else
            echo "PST in effect"
            echo "daylight_savings_bool=false" >> $GITHUB_OUTPUT
          fi
